### ISSUE TITLE
Need git@ for yarn add in package.json

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/vue-cli-plugin-quasar#1]
url": "git+https://git@github.com/quasarframework/vue-cli-plugin-quasar.git"

**Comment by rstoenescu** [comment]
The plan is to publish "vue-cli-plugin-quasar" npm package.

**Comment by nothingismagick** [comment]
Yes, I know. Then it’s probably better to delete that line from the package.json - because as it is it won’t work if anyone tries it.

**Comment by nothingismagick** [comment]
Oops - that should have read ssh - not https I didn’t read clearly. Sry
