### ISSUE TITLE
Impossible to change color on ajaxbar

### ISSUE THREAD

**Issue by mdeprezzo** [quasarframework/vue-cli-plugin-quasar#13]
### Software version

Quasar: 0.17.19
vue-cli-plugin-quasar: 0.17.1
OS: Ubuntu 18.04
Node: 8.12.0
NPM: 6.4.1

### What did you get as the error?
setDefaults on this.$q.loadingBar is not a function

### What were you expecting?
To change color of the ajaxbar

### What steps did you take, to get the error?
on mounted hook:

```
this.$q.loadingBar.setDefaults({color: 'green'})
```

And this is my vue config file:

```
  pluginOptions: {
    quasar: {
      theme: 'mat',
      rtlSupport: true,
      importAll: true,
      extras: [
        'material-icons',
        'mdi',
        'ionicons',
        'fontawesome'
      ],
      loadingBar: {
        position: 'bottom',
        color: 'green'
      }
    },
    cordovaPath: 'src-cordova'
  },
[...]
```
but nothing happen, after build and the option loadingBar it seems to be ignored

**Comment by rstoenescu** [comment]
Hi,

Use the `config: {}` Object to specify your loadingBar config. Should be in main.js/ts near the `Vue.use(Quasar, {...`
