### ISSUE TITLE
fix the vue-cli template support with quasar v1.0.0@beta.4

### ISSUE THREAD

**Issue by alterhu2020** [quasarframework/vue-cli-plugin-quasar#15]
### Software version

Quasar: 1.0.0.beta.4
vue-cli-plugin-quasar: quasar@beta 
OS:
Node:
NPM:
Any other software related to your bug:

### What did you get as the error?
When install the vue-cli-plugin-quasar as reading from : https://v1.quasar-framework.org/start/vue-cli-plugin,
```
vue add quasar@beta
```
Then the install completed successfully ,but quasar feature had not added into existing project. it's not working, Could you try to update the correct data for V1.0.0 template ? thanks .
### What were you expecting?
Support quasar v1.0.0@beta.4 feature
### What steps did you take, to get the error?
Not added any dependencies, not work.

**Comment by rstoenescu** [comment]
`vue add quasar@beta` then `vue invoke quasar` --- invoke required because of bug in vue-cli.

**Comment by alterhu2020** [comment]
@rstoenescu thanks, sorry I didn't notice the line in the document:`vue invoke quasar`. 
Anyway, it works.
