### ISSUE TITLE
[v1 - Request] Make file name `quasar-variables.styl` the same name as in import directive

### ISSUE THREAD

**Issue by DmitrijOkeanij** [quasarframework/vue-cli-plugin-quasar#16]
Now file name has name `quasar.variables.styl`
But if I need to import it, I need to make this `@import 'quasar-variables'`
In first place there is `.` (dot), in second `-` (dash)
Different naming in unclear and strange.

I think It will be good to make in both places the same way.

**Comment by rstoenescu** [comment]
Fixed it in vue-cli-plugin-quasar v1.0.0-beta.1 (will be available shortly).
There is a breaking change though. In `/src/styles/quasar.variables.styl`, you need to change:

```stylus
@import '~quasar-variables'
```
to
```stylus
@import '~quasar-variables-styl'
```
