### ISSUE TITLE
Support yarn workspaces

### ISSUE THREAD

**Issue by leo-buneev** [quasarframework/vue-cli-plugin-quasar#17]
**Describe the bug**
When using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) to create a repo project is impossible to build ("failed to locate @import file ~quasar-variables-styl.styl").

The reason for it - with yarn workspaces node_modules folder is supposed to be not in project root but one level higher. For example:

```
/node_modules    // modules from all "packages/*" are stored here
/packages
  /quasar-app
    /App.vue
    /vue.config.js
    /package.json
/package.json
``` 

This behaviour is supported by node.js webpack module resolution algorithm. However, vue-cli-plugin-quasar uses direct file webpack alias in /index.js:

```
chain.resolve.alias
      .set(
        'quasar-variables-styl',
        // problem - node_modules doesn't exist in current directory
        api.resolve('node_modules/quasar/src/css/variables.styl') 
      )
```
I believe it would be enough to change this alias to use module reference instead of direct path reference - and will even look cleaner

```
chain.resolve.alias
      .set(
        'quasar-variables-styl',
        'quasar/src/css/variables.styl' 
      )
```

**To Reproduce**
1. Clone https://github.com/leo-buneev/vue-cli-plugin-quasar-yarn-workspaces-issue-reproduction
2. yarn install
3. cd packages/quasar-app
4. yarn serve

**Expected behavior**
Project builds

**Screenshots**

**Platform (please complete the following information):**
OS: MacOS
Node: 11.11.0
NPM: 6.4.1
Yarn: 1.15.2

**Comment by rstoenescu** [comment]
Please update `vue-cli-plugin-quasar` to version `1.0.0-rc.2` and let me know how it goes. Thanks!

**Comment by leo-buneev** [comment]
Works great, thanks for fast response.

Just for info, for whoever will find this issue in the future - there is one more issue currently related to postcss and vue cli (not related to quasar itself), that prevents using yarn workspaces with vue cli. to fix it, add this in your vue.config.js:

```
css: {
    loaderOptions: {
      postcss: {
        config: {
          path: '.',
        },
      },
    },
  },
```

**Comment by rstoenescu** [comment]
I'm actually on that too. Will try something in the next days so no extra config will be required.

**Comment by rstoenescu** [comment]
Enhanced that too in `@quasar/extras` v1.1.4. @leo-buneev
