### ISSUE TITLE
Postcss can't recognice postcss.config.js after a clean install

### ISSUE THREAD

**Issue by koletzilla** [quasarframework/vue-cli-plugin-quasar#18]
To start with, thanks for all the efforts with Quasar!! It's a pretty nice framework and I really like how it works :D I have tried to fix this, trying to modify the config file and looking in the dependencies, but I haven't found the cause :(.

**Describe the bug**
After creating a clean project, doing an `npm run serve` or `yarn serve` prints this in the console:

`You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.`

There is actually an autogenerated `postcss.config.js` in the root folder and the command finish as expected, with the webserver running and aparently the web renders correctly, but I don't know if there are hidden visuals broken or something incorrect because of this postcss problem.

**To Reproduce**
I have attached the console output with the commands so you can directly see the steps I have used to reproduce it, but basically:
1º) Create vue project with Babel, Router, Linter and Unit, No history, Prettier, Lint on Save, different config files, and NPM (I have tried yarn, with same results)
2º) Add Quasar plugin: Allow quasar to replace files, treeshaking, no RTL support, Material Icon Set, and `es` lang.

3º) Running the `npm run serve` shows the postcss problem.

[console_output.txt](https://github.com/quasarframework/vue-cli-plugin-quasar/files/3423529/console_output.txt)

**Expected behavior**
Not show that warning. As it looks like postcss is not working now, I guess it should work with `serve` but I don't even know where it applies, so I'm not sure If we just can delete that postcss plugin or just ignore the error.

**Screenshots**
Code attached

**Platform (please complete the following information):**
OS: MacOS Mojave 10.14.5
Node: v10.15.3
NPM: 6.10.1
Yarn:1.17.3
Browsers: -- 
iOS: -- 
Android: -- 
Electron: -- 

**Additional context**
It looks like if I create the project directly with quasar-cli I don't have this problem, but I prefer the vue-cli option to create the project.

**Comment by icksky** [comment]
I alse fell into this problem when I tried to update quasar v0.17 to v1.0. 
And I found out my problem is recycle import in `/src/style/quasar.variables.styl` because of webpack alias settings. **check out the alias named `quasar-variables`**. I changed `@import '~quasar-variables'` to `@import '~quasar-variables-styl'` and solved this problem.
```javascript
// the setting of v0.17
chain.resolve.alias
      .set(
        'quasar',
        importAll
          ? api.resolve(`node_modules/quasar-framework/dist/quasar.${theme}.esm.js`)
          : 'quasar-framework'
      )
      .set('variables', api.resolve(`src/styles/quasar.variables.styl`))
      .set('quasar-variables', api.resolve(`node_modules/quasar-framework/src/css/core.variables.styl`))
      .set('quasar-styl', api.resolve(`node_modules/quasar-framework/dist/quasar.${theme}.styl`))
      .set('quasar-addon-styl', api.resolve(`node_modules/quasar-framework/src/css/flex-addon.styl`))
```
```javascript
// the setting of v1.0
chain.resolve.alias
      .set(
        'quasar-variables',
        api.resolve('src/styles/quasar.variables.styl')
      )
      .set(
        'quasar-variables-styl',
        'quasar/src/css/variables.styl'
      )
      .set(
        'quasar-styl',
        'quasar/dist/quasar.styl'
      )
      .set(
        'quasar-addon-styl',
        'quasar/src/css/flex-addon.styl'
      )
```

**Comment by koletzilla** [comment]
Hi! Thanks for your response.
In my case, `/src/styles/quasar.variables.styl` already have `@import '~quasar-variables-styl'`.

I don't have defined anything related to `chain.resolve` stuff in my `vue.config.js`, but I have tried to add it like:

```javascript
var path = require("path");

module.exports = {
  pluginOptions: {
    quasar: {}
  },
  transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/],
  chainWebpack: config => {
    // the setting of v1.0
    config.resolve.alias
      .set(
        "quasar-variables",
        path.resolve(__dirname, "src/styles/quasar.variables.styl")
      )
      .set("quasar-variables-styl", "quasar/src/css/variables.styl")
      .set("quasar-styl", "quasar/dist/quasar.styl")
      .set("quasar-addon-styl", "quasar/src/css/flex-addon.styl");
  }
};
```
But `npm run serve` is still giving me that message about postcss :(

**Comment by koletzilla** [comment]
I have been continuing trying other things. It looks like the problem could be related to the `icons` used. If I select the Material Icons set, the message is:
```
 40% building 144/147 modules 3 active ...xtras/material-icons/material-icons.cssYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```
The Postcss message came just after the css icons path. If I change the `Material icons` for another set of icons, the postcss message came just after one of the css files of this new icons set. Could it be related?

**Comment by emprove** [comment]
Any update on this? Im also have this issue on clean vue project (vue create & vue add quasar).

**Comment by rstoenescu** [comment]
This should be fixed with v2 of vue-cli-plugin-quasar.
If it still persists, then it's a misusage somewhere in your project files.
