### ISSUE TITLE
error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js

### ISSUE THREAD

**Issue by ejez** [quasarframework/vue-cli-plugin-quasar#20]
**Describe the bug**
After running `vue add quasar`, I am getting these errors:
```bash
⠋  Running completion hooks...error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js:11:31:
   9 |   },
  10 | 
> 11 |   transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
     |                               ^
  12 | };
  13 | 


error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js:11:49:
   9 |   },
  10 | 
> 11 |   transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
     |                                                 ^
  12 | };
  13 | 


error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js:11:61:
   9 |   },
  10 | 
> 11 |   transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
     |                                                             ^
  12 | };
  13 | 


3 errors found.

```

**To Reproduce**
1. add a vue cli project: `vue create my-project`
2. `cd my-project`
3. Add quasar plugin: `vue add quasar`

`vue.config.js` now contains:
```js
  transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
```

**Comment by uxcode1** [comment]
Same issue.

**Comment by ejez** [comment]
Instead of using a regex, we can keep it simple by using a string:

 `generator/index.js`
```diff
-    transpileDependencies.push(/[\\/]node_modules[\\/]quasar[\\/]/)
+    transpileDependencies.push('quasar')
```
(`node_modules` will be added automatically, see https://github.com/vuejs/vue-cli/blob/48dd88affa95b90e74353c5507b38fcbb9fa99ce/packages/%40vue/cli-plugin-babel/index.js#L7)

If a regular expression is still needed for some reason we can use:
```diff
-    transpileDependencies.push(/[\\/]node_modules[\\/]quasar[\\/]/)
+    transpileDependencies.push(/node_modules\/quasar\//)
```
which will do exactly the same as using a string

**Comment by hugetiny** [comment]
It's ok to add quasar plugin with @vue/cli3, but failed with @vue/cli4

**Comment by rstoenescu** [comment]
Support for @vue/cli v4 will come with vue-cli-plugin-quasar v2 (fixed there already; will be released soon).
