### ISSUE TITLE
TypeError: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by petronellius** [quasarframework/vue-cli-plugin-quasar#22]
**Describe the bug**
Runtime error in browser console when using Vue CLI + Typescript.

**To Reproduce**
Steps to reproduce the behaviour (follow https://quasar.dev/start/vue-cli-plugin):
1. Use Vue CLI to create new Typescript app (vue create my-app)
2. Add quasar plugin (vue add quasar)
3. Run yarn serve
4. Open browser with application

Nothing will display and error will be in browser console.

Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.Vue.use (vue.runtime.esm.js?2b0e:5100)
    at eval (quasar.js?1288:23)
    at Module../src/quasar.js (app.js:1040)
    at __webpack_require__ (app.js:786)
    at fn (app.js:151)
    at eval (main.ts?3d1f:1)
    at Module../src/main.ts (app.js:1028)
    at __webpack_require__ (app.js:786)
    at fn (app.js:151)
    at Object.1 (app.js:1065)

**Expected behavior**
When I use babel instead of TypeScript when app is created, everything is working.

**Platform (please complete the following information):**
Vue CLI: 4.0.5
Quasar: 1.2.7
Typescript: 3.5.3

**Additional context**
Tree-shaking is also not working when using Typescript.

**Comment by petronellius** [comment]
I solved the problem by creating new project through Vue CLI as "Use Babel alongside TypeScript...". Then Babel is used to compile Quasar without any error during runtime. Even three-shaking is working now. If I understand is well, Babel is do it through transform-imports plugin. So it imports only used modules not whole Quasar (trough index.js). 
This should be definitely documented in Quasar doc. It will save a lot of time for Vue, Quasar and Babel beginner.

**Comment by rstoenescu** [comment]
Added this to the docs. Will be available on next docs deployment.
Glad that you figured it out.
