### ISSUE TITLE
Sass compilation is failing with Quasar version 1.2.7

### ISSUE THREAD

**Issue by sdcdsvsdv423** [quasarframework/vue-cli-plugin-quasar#23]
**Describe the bug**
I am getting the following error during compilation:
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                   11:09:55 PM

 error  in ./src/styles/quasar.sass

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected expression.
   ╷
48 │   border-bottom: none /* 1 */
   │                        ^
   ╵
  node_modules/quasar/src/css/normalize.sass 48:24  @import
  node_modules/quasar/src/css/index.sass 2:9        @import
  /Users/esindger/www/test/quasar-sass-test/src/styles/quasar.sass 2:9
```

**To Reproduce**
1. Clone https://github.com/esindger/quasar-sass-test
2. Run `npm run serve`

**Expected behavior**
Successful compilation.

**Screenshots**
<img width="834" alt="Снимок экрана 2019-10-29 в 22 59 04" src="https://user-images.githubusercontent.com/5320711/67780211-b92dab00-faa0-11e9-8975-1e04b0f3db0a.png">

**Platform (please complete the following information):**
OS: macOS 10.15
Node: 12.7.0
NPM: 6.10
Vue-Cli: 4

**Comment by rstoenescu** [comment]
That file that Sass is complaining about hasn't changed in a few years.
Have you recently upgraded to vue-cli v4?

**Comment by sdcdsvsdv423** [comment]
It's new project, I haven't tried this code on vue-cli v3.
This is version of sass-related packages:

`node-sass`: 4.13.0
`sass-loader`: 8.0.0

**Comment by sdcdsvsdv423** [comment]
The error is dissapear if to change inline comments style. This code is working:

```sass
abbr[title]
  border-bottom: none // 1
  text-decoration: underline // 2
  text-decoration: underline dotted // 2
```

[Source](https://github.com/quasarframework/quasar/blob/31808ac99b68f02280561ae16134015cc55227d8/ui/src/css/normalize.sass#L40-L43)

**Comment by sdcdsvsdv423** [comment]
Error occures only with `dart-sass`. Compilation with `node-sass` works properly.
