### ISSUE TITLE
LocalStorage warning  in ./node_modules/quasar/src/plugins/LocalStorage.js  "export 'client' was not found in './Platform.js'

### ISSUE THREAD

**Issue by DiaaEddin** [quasarframework/vue-cli-plugin-quasar#25]
**Describe the bug**
I am using Quasar 1.2.4 installed via vue-cli when I tried to import LocalStorage I got the followeing error in the terminal when running `npm run serve`:

> warning  in ./node_modules/quasar/src/plugins/LocalStorage.js 
> "export 'client' was not found in './Platform.js'

and the following error message in the browser console:

> Uncaught TypeError: Cannot read property 'has' of undefined
>     at Object.install (webpack-internal:///./node_modules/quasar/src/plugins/LocalStorage.js:9)
>     at eval (webpack-internal:///./node_modules/quasar/src/install.js:91)
>     at Array.forEach (<anonymous>)
>     at Object.eval [as install] (webpack-internal:///./node_modules/quasar/src/install.js:87)
>     at Function.Vue.use (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5091)
>     at eval (webpack-internal:///./src/quasar.js:117)
>     at Module../src/quasar.js (app.js:7539)
>     at __webpack_require__ (app.js:727)
>     at fn (app.js:101)
>     at eval (webpack-internal:///./src/main.ts:12)

**Codepen/jsFiddle/Codesandbox (required)**
***quasar.js***
```javascript
import {
    Quasar,
    LocalStorage,
    ...
} from 'quasar';

Vue.use(Quasar, {
    config: {},
    plugins: {
        LocalStorage,
        ...
    },
    ...
};
```

**Comment by rstoenescu** [comment]
Vue-cli has a bug with their caching where it requires you to delete node_modules (possibly yarn.lock or package-lock.json) and install again after an upgrade.
