### ISSUE TITLE
auto-import with transform-imports

### ISSUE THREAD

**Issue by psi-4ward** [quasarframework/vue-cli-plugin-quasar#33]
I'm not able to get the babel-plugin `transform-imports` working:

babel.config.js
```javascript
module.exports = {
  "presets": [
    "@vue/cli-plugin-babel/preset"
  ],
  "plugins": [
    [
      "transform-imports",
      {
        "quasar": {
          "transform": require("quasar/dist/babel-transforms/imports.js"),
          "preventFullImport": true
        },
      }
    ]
  ]
}
```
It just triggers once for `import { Quasar } from 'quasar';` (from my src) and ignores all import statements generated by auto-import.

But nevertheless, I wonder why the loader generates `import {...} from 'quasar'` statements instead of `import QBtn from quasar/src/src/components/btn/QBtn.js`? 
I think this would be easy to implement and reduces the bundle size.

**Comment by rstoenescu** [comment]
Fix will be available today in "vue-cli-plugin-quasar" v3.0.0.
Please read the upgrade guide (after released).
