### ISSUE TITLE
Cannot Read Property of Undefined

### ISSUE THREAD

**Issue by delaclqm** [quasarframework/vue-cli-plugin-quasar#35]
Description:
I am trying to have a CSS class become toggled at a specific scroll position. So to accomplish this I have bound to the mounted lifecycle method to add an event listener to the window like this...

```
mounted: () => {
    window.addEventListener("scroll", this.updateScroll);
}
```

It then calls the updateScroll method which will update the property called scrollPosition in my component (for more context, please look at full component code at bottom). However, when I am running it, I get the following error from inside my mounted function...

![image](https://user-images.githubusercontent.com/44246223/90702316-eed29900-e258-11ea-9c91-4252cb6446ef.png)

Even weirder is that when I place a breakpoint on the invocation of that method and try to see the value of 'this' it shows me that the updateScroll method exists.

![image](https://user-images.githubusercontent.com/44246223/90702465-57ba1100-e259-11ea-86d8-a2aa344c6b20.png)

As I am new to Vue and am mainly an Angular developer, even before I tried to see if the component was instantiated at the point when the component mounts, I thought to put in a console.log(this); right before adding the event listener to the page scroll and I got this from the dev tools...

![image](https://user-images.githubusercontent.com/44246223/90702659-c6976a00-e259-11ea-9d48-2d0b868d1424.png)

But yet the console output was 'undefined';

I then tried to make this same flow in a very basic component and was able to repeat this exact same issue. Any help would be greatly appreciated and I apologize if this is a simple fix, I am still learning Quasar and Vue.

Expected Behavior:
I would have expected that the method would not be undefined considering that the dev tools said that 'this' had updateScroll as a function.

Platform (please complete the following information):
OS: Windows 10
Browsers: Chrome
Versions from package.json

```
"dependencies": {
    "@quasar/cli": "^1.0.5",
    "@quasar/extras": "^1.6.0",
    "atob": "^2.1.2",
    "aws-sdk": "^2.610.0",
    "axios": "^0.19.0",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.3",
    "canvas": "^2.6.1",
    "core-js": "^2.6.9",
    "express": "latest",
    "express-throttle-bandwidth": "latest",
    "firebase": "^6.6.2",
    "formidable": "latest",
    "gyp": "^0.5.0",
    "ipfs-http-client": "^38.2.0",
    "node-gyp": "^6.0.0",
    "node-sass": "^4.13.1",
    "popper.js": "^1.15.0",
    "quasar": "^1.9.11",
    "rebuild": "^0.1.2",
    "sha256": "^0.2.0",
    "vue": "^2.6.11",
    "vue-pdf": "^4.0.7",
    "vuex": "^3.1.2",
    "web3": "^1.2.1"
  },
  "devDependencies": {
    "@quasar/app": "^1.6.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.10.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^5.0.0",
    "strip-ansi": "=3.0.1",
    "vue-analytics": "^5.22.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0",
    "yarn": ">= 1.6.0"
  },
  "browserslist": [
    "> 1%",
    "last 1 version, not dead, ie >= 11",
    "not ie <= 10"
  ]
```

Full Script for Component
```
<script>
import AuthService from "../services/AuthService.js";

export default {
  name: "NavigationBar",
  components: {
    "sign-up-dialog": require("./Dialog/SignUpDialog.vue").default,
    "add-content-dialog": require("./Dialog/AddContentDialog.vue").default,
    "drawer-content": require("../layouts/Drawer.vue").default,
    "auth-dialog": require("./Dialog/AuthDialog.vue").default,
    "layer-builder": require("./Search/LayerBuilder.vue").default,
  },
  data: () => {
    return {
      scrollPosition: null,
      leftDrawerOpen: false,
      validLogin: true,
      addContent: false,
      signUpPopup: false,
      loginPopup: false,
      dark: false,
      searchText: "",
      filterParam: "title",
      paramList: ["title", "author", "school", "prof", "textbook"],
    };
  },
  methods: {
    join() {
      this.signUpPopup = true;
    },
    async logout() {
      await AuthService.logoutUser();
      await this.$router.push("/");
    },
    expandSearch() {},
    updateScroll() {
      this.scrollPosition = position;
    },
  },
  computed: {
    userDetails() {
      return this.$store.getters["auth/userDetails"];
    },
  },
  //======================= Lifecycle Methods
  mounted: () => {
    window.addEventListener("scroll", this.updateScroll);
  },
};
</script>
```

**Comment by nklayman** [comment]
Instead of using an arrow function to define the `mounted` hook, use a regular one:
```js
mounted() {
    window.addEventListener("scroll", this.updateScroll);
}
```

See [this page of the Vue docs](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks) for more details (read the warning about arrow functions). See [this page](https://javascript.info/arrow-functions) for more details about arrow functions.
