### ISSUE TITLE
Compilation error on fresh install when using TypeScript

### ISSUE THREAD

**Issue by ckaik** [quasarframework/vue-cli-plugin-quasar#4]
Hi,

I've been trying to setup quasar in my vue project using this plugin but I'm running into an issue. This is from a fresh install using the plugin on a brand new project set up using vue cli 3.0.0 rc3.

This only happens with TypeScript. Vue CLI projects without TypeScript work fine.

```
ERROR in /Users/user/my-app/src/main.ts
6:30 Cannot find module 'quasar'.
    4 | import './styles/quasar.styl'
    5 | import 'quasar-extras/material-icons'
  > 6 | import Quasar, * as All from 'quasar'
      |                              ^
    7 |
    8 | Vue.use(Quasar, {
    9 |   components: All,
Version: typescript 2.9.2
```

**Steps to reproduce**

```
vue create my-app
```

Options:

* with TS
* class style components
* babel polyfills
* dedicated config files

```
vue add quasar
```

Options:

* iOS Theme
* Allow Replace
* Import All Plugins/Components
* Material Icons

**Comment by murbanowicz** [comment]
You didn't declare Quasar in types. This is all you have to do.

In shims-vue.d.ts
```js
declare module 'quasar'
declare module 'quasar-framework/*'
```

**Comment by rstoenescu** [comment]
Typescript is not yet supported out of the box.
