### ISSUE TITLE
babel-transforms path moved in quasar@next

### ISSUE THREAD

**Issue by psi-4ward** [quasarframework/vue-cli-plugin-quasar#40]
Hi,

the files of auto-import has been moved in quasar@next:

```
quasar/dist/babel-transforms/auto-import.json -> quasar/dist/transforms/auto-import.json
quasar/dist/babel-transforms/imports.js -> quasar/dist/transforms/import-transformation.js
```

can we support the new locations too?

**Comment by rstoenescu** [comment]
The quasar@next is for Quasar v2 (and Vue 3), which is currently not released to the general public. But, of course there will be a vue cli plugin version for Quasar v2 when it will become public. You just need to be patient.

**Comment by psi-4ward** [comment]
Probably we should keep this issue open for interested users.
Looks like most of the stuff works

**Comment by imaneumma** [comment]
Facing the same issue on Quasar migration from 1 to 2. Which version should be used?

**Comment by rstoenescu** [comment]
@imaneumma why do you care about this? this is handled automatically..

For anyone reading, do not use "quasar@next". That was needed when Quasar v2 was in the early stages.
