### ISSUE TITLE
app runs failed when @vue/cli version is greater than or equal to 4.5.0

### ISSUE THREAD

**Issue by fengjac** [quasarframework/vue-cli-plugin-quasar#42]
**Describe the bug**
I have used @vue/cli and this Vue CLI Plugin to init my new project. It works well when @vue/cli version is 4.0.0 or 4.4.0.
But app runs failed when @vue/cli version is greater than or equal to 4.5.0.

Here is the warning show in cmd when app is running:

>  WARNING  Compiled with 1 warning
> 
>  warning  in ./src/quasar.js
> 
> "export 'default' (imported as 'Vue') was not found in 'vue'
> 
> 
>   App running at:
>   - Local:   http://localhost:8080/
>   - Network: http://10.20.34.75:8080/
> 
>   Note that the development build is not optimized.
>   To create a production build, run npm run build.

And then visit http://localhost:8080 in chrome, it shows error in the browser console like:

> Uncaught TypeError: Cannot read property 'extend' of undefined
>     at eval (QPage.js?9989:7)
>     at Module../node_modules/quasar/src/components/page/QPage.js (chunk-vendors.js:2371)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)
>     at eval (HelloWorld.vue?82e3:1)
>     at Module../src/components/HelloWorld.vue (app.js:1055)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)
>     at eval (App.vue?3dfd:85)
>     at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-cli-plugin-quasar/lib/loader.transform-quasar-imports.js!./node_modules/vue-cli-plugin-quasar/lib/loader.auto-import.js?kebab!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/App.vue?vue&type=script&lang=js (app.js:938)

**To Reproduce**
1. npm uninstall @vue/cli -g
2. npm install @vue/cli -g
3. vue create my-new-vue-project [Default (Vue 3 Preview) ([Vue 3] babel, eslint)]
4. cd my-new-vue-project
5. vue add quasar [
? Allow Quasar to replace App.vue, About.vue, Home.vue and (if available) router.js? Yes
? Pick your favorite CSS preprocessor: SCSS
? Choose Quasar Icon Set Material
? Default Quasar language pack - one from https://github.com/quasarframework/quasar/tree/dev/ui/lang en-us
? Use RTL support? No
? Select features:
]
6. npm run serve
7. visit http://localhost:8080 in Chrome browser

**Expected behavior**
I am not sure what is wrong with it. It should work well like when @vue/cli version is 4.4.0 or 4.0.0

**Platform (please complete the following information):**
OS: Windows 10 porfessional
Node: v14.15.1
NPM: 6.14.8
Yarn: 1.22.10
Browsers: Chrome Version 85.0.4183.121 (Official Build) (32-bit)

Thank you!

**Comment by rstoenescu** [comment]
Hi,

1. What is the version of vue-cli-plugin-quasar that you are using? Also what vue version?
2. If you've upgraded to latest vue-cli-plugin-quasar v4.0.0 then make sure that you read the instructions on https://next.quasar.dev/start/upgrade-guide -- seems to me that you're initializing Quasar the old way (v1, instead of v2)

**Comment by rstoenescu** [comment]
Closing due to lack of feedback.
