### ISSUE TITLE
Error on install with yarn 1.9.2

### ISSUE THREAD

**Issue by NiQ-B** [quasarframework/vue-cli-plugin-quasar#5]
### Software version

Quasar:
vue-cli-plugin-quasar: 0.2.1
OS: Linux Ubuntu 16.04
Node: 10.7.0
NPM: 6.0.0
Yarn: 1.9.2
Any other software related to your bug: Yarn: 1.9.2

### What steps did you take, to get the error? installation instructions.

vue add quasar

📦  Installing vue-cli-plugin-quasar...

yarn add v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ vue-cli-plugin-quasar@0.2.1
Done in 3.77s.
✔  Successfully installed plugin: vue-cli-plugin-quasar

? Select Quasar Theme: iOS Theme
? Allow Quasar to replace App.vue, About.vue, Home.vue and (if available) router.js? Yes
? Import all Quasar components, directives and plugins? Yes
? Use RTL support? Yes
? Choose Icon Set Fontawesome
? Quasar i18n lang - one from https://github.com/quasarframework/quasar/tree/dev/i18n en-us
? Select features: Animations, Fontawesome, Ionicons

🚀  Invoking generator for vue-cli-plugin-quasar...
📦  Installing additional dependencies...

yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error quasar-framework@0.17.6: The engine "yarn" is incompatible with this module. Expected version ">= 1.6.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ERROR  command failed: yarn add -D vue-cli-plugin-quasar

Installed vue-cli-plugin-quasar and quasar-extras manually without error. Builds without error but the demo doesn't show in the browser and errors to numerous to include in the console.

**Comment by NiQ-B** [comment]
Update: 
Altered ~/.vuerc
packageManager: "npm" from "yarn"

rebuilt the project and installed the plugin following the directions in the installation guide.

All went well and the generator ran without issue. Seems to be a problem with as stated above with the acceptable version of yarn. 

A workaround is to change the packageManager for projects to npm.

**Comment by rstoenescu** [comment]
Hi, Your yarn is 1.3.2, not 1.9.2. 1.6.0 is the minimum version required. Check the logs.

**Comment by NiQ-B** [comment]
Hey @rstoenescu was just about to update and close thanks for the quick response.  

Had two versions installed one manual install and apt-get from Ubuntu. 
Weird my local path stated version 1.9.2, vue add was pointing to /usr/local/bin/yarn.

One other gotcha if you're  installing into a @vue/cli 3.0.x project is if the project uses configureWebpack in a vue.config.js file the aliases do not get created, which causes errors in the build can't resolve quasar.

Thanks again!
