### ISSUE TITLE
QSpinner is not pointing to QSpinner.mat or QSpinner.ios by default

### ISSUE THREAD

**Issue by jcperez-ch** [quasarframework/vue-cli-plugin-quasar#8]
### Software version

Quasar: 0.17.12
OS: Mac OS
Node: 10.0
NPM: 6.3.0
Browsers: Chrome/Safari
Any other software related to your bug:

### What were you expecting?
Normal behaviour when not importing the QSpinner, since it's a dependency of QInput, either that or update the docs to add manually the dependency to QSpinner

### What steps did you take, to get the error?
After installing a brand new project using the Vue Cli 3, or updating to version 0.17.9 and adding the QSpinner as [shown in the docs](https://quasar-framework.org/components/spinner.html), Vue complains as:

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'components' of undefined"

found in

---> <QInput>
```

Same issue happens in `QUploader`, `QBtn` when using the `loading` flag.

This is because in the webpack chain we are merging and not prepanding:

`index.js`
```
chain.resolve.extensions
        .merge([ `.${theme}.js` ])
```
it should be:

```
chain.resolve.extensions.prepend(`.${theme}.js`)
```

I can add the fix and test it...

**Comment by rstoenescu** [comment]
Thanks for reporting. The previous code dealing with this needed tweaks. Released vue-cli-plugin-quasar v0.17.1 fixing this.
