### ISSUE TITLE
Not so clear where to set i18n lang and other quasar.conf.js params

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/vue-cli-plugin-quasar#9]

**Comment by rstoenescu** [comment]
Hi,

`quasar.conf.js` is a feature available only through Quasar CLI. It is NOT used when choosing the vue-cli path.

**Comment by eladcandroid** [comment]
So how can I set i18n parameter alternatively?

**Comment by rstoenescu** [comment]
If when you added vue-plugin-cli-quasar you've chosen to import full Quasar then:
```js
import Quasar from 'quasar'
// ---> Quasar.i18n.set(lang)
```
Otherwise:
```js
import { Quasar } from 'quasar'
// ---> Quasar.i18n.set(lang)
```

Alternatively, you can also set i18n language when installing Quasar Vue plugin:
```
import langDE from 'quasar-framework/i18n/de'
Vue.use(Quasar, { .... i18n: langDE ... }
```
